import type { Metadata } from 'next';
import { IBM_Plex_Sans } from 'next/font/google';
import './globals.css';
import PageLayout from '@/components/layout/PageLayout';
import ClientScrollProvider from '@/components/providers/ClientScrollProvider';

const ibmPlexSans = IBM_Plex_Sans({
  weight: ['300', '400', '500', '700'],
  variable: '--font-ibm-plex-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${ibmPlexSans.variable} antialiased`}>
        <ClientScrollProvider>
          <PageLayout>{children}</PageLayout>
        </ClientScrollProvider>
      </body>
    </html>
  );
}
